# Generated by Django 5.1.2 on 2024-10-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0002_projectplan_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_evento', models.CharField(choices=[('trabajo', 'Día de trabajo'), ('entrega', 'Entrega'), ('reunión', 'Reunión')], max_length=50)),
            ],
        ),
    ]
