# Generated by Django 5.1.1 on 2024-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creadorAPP", "0002_projectplan_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectplan",
            name="presupuestoTotal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Presupuesto total del proyecto en USD.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
