# Generated by Django 5.1.1 on 2024-10-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creadorAPP", "0003_projectplan_presupuestototal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restriccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(help_text="Descripcion de la restricción."),
                ),
                (
                    "riesgo_identificado",
                    models.TextField(help_text="Riesgo asociado con esta restricción."),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restricciones",
                        to="creadorAPP.projectplan",
                    ),
                ),
            ],
        ),
    ]
