# Generated by Django 5.1.2 on 2024-10-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0003_eventocronograma'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsfuerzoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esfuerzo_estimado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('esfuerzo_real', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creadorAPP.projectplan')),
            ],
        ),
    ]
