# Generated by Django 5.1.2 on 2024-11-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creadorAPP", "0006_remove_projectplan_employeename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restriccion",
            name="riesgo_identificado",
        ),
    ]
