# Generated by Django 5.1.1 on 2024-11-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0008_projectplan_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrisks',
            name='probability',
            field=models.CharField(choices=[('low', 'Baja'), ('meduim', 'Media'), ('high', 'Alta')], default='low', max_length=10),
            preserve_default=False,
        ),
    ]
