# Generated by Django 5.1.1 on 2024-11-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0009_projectrisks_probability'),
        ('creadorAPP', '0009_restriccion_tipo_riesgo_and_more'),
    ]

    operations = [
    ]
