# Generated by Django 5.1.3 on 2024-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0010_merge_20241113_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrisks',
            name='mitigation_strategy',
            field=models.CharField(choices=[('avoid', 'Evitar'), ('accept', 'Aceptar'), ('transfer', 'Transferir'), ('control', 'Controlar')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
