# Generated by Django 5.1.2 on 2024-11-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0007_projectrisks_mitigation_strategy_accept_and_more'),
        ('creadorAPP', '0011_projectrisks_mitigation_strategy'),
    ]

    operations = [
    ]
