# Generated by Django 5.1.2 on 2024-11-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0012_merge_20241118_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrisks',
            name='mitigation_strategy_accept',
        ),
        migrations.RemoveField(
            model_name='projectrisks',
            name='mitigation_strategy_avoid',
        ),
        migrations.RemoveField(
            model_name='projectrisks',
            name='mitigation_strategy_control',
        ),
        migrations.RemoveField(
            model_name='projectrisks',
            name='mitigation_strategy_transfer',
        ),
        migrations.AlterField(
            model_name='projectrisks',
            name='mitigation_strategy',
            field=models.CharField(choices=[('avoid', 'Evitar'), ('Aceptar', 'Aceptar'), ('transfer', 'Transferir'), ('control', 'Controlar')], max_length=10),
        ),
    ]
