# Generated by Django 5.1.1 on 2024-11-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0010_merge_20241113_1236'),
        ('creadorAPP', '0013_remove_projectrisks_mitigation_strategy_accept_and_more'),
    ]

    operations = [
    ]
