# Generated by Django 5.1.2 on 2024-11-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0013_remove_projectrisks_mitigation_strategy_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectrisks',
            name='mitigation_strategy',
            field=models.CharField(choices=[('Evitar', 'Evitar'), ('Aceptar', 'Aceptar'), ('Transferir', 'Transferir'), ('Controlar', 'Controlar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectrisks',
            name='probability',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectrisks',
            name='risk_type',
            field=models.CharField(choices=[('Técnico', 'Técnico'), ('Organizativo', 'Organizativo'), ('Financiero', 'Financiero')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectrisks',
            name='severity_level',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Recursos Humanos', 'Recursos Humanos'), ('Herramientas y Software', 'Herramientas y Software'), ('Infraestructura y Servicios', 'Infraestructura y Servicios'), ('Presupuesto', 'Presupuesto'), ('Documentación y Procedimientos', 'Documentación y Procedimientos')], max_length=30, verbose_name='Tipo de Recurso'),
        ),
        migrations.AlterField(
            model_name='restriccion',
            name='tipo_riesgo',
            field=models.CharField(blank=True, choices=[('Técnico', 'Técnico'), ('Organizativo', 'Organizativo'), ('Financiero', 'Financiero')], help_text='Tipo de riesgo asociado con esta restricción.', max_length=30, null=True, verbose_name='Tipo de Riesgo'),
        ),
        migrations.AlterField(
            model_name='workteammember',
            name='role',
            field=models.CharField(choices=[('Gestor del proyecto', 'Gestor del proyecto'), ('Desarrollador', 'Desarrollador'), ('Analista', 'Analista'), ('QA Tester', 'QA Tester'), ('Otro', 'Otro')], max_length=75, verbose_name='Rol del miembro del equipo'),
        ),
        migrations.CreateModel(
            name='EsfuerzoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esfuerzo_estimado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('esfuerzo_real', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creadorAPP.projectplan')),
            ],
        ),
    ]
