# Generated by Django 5.1.2 on 2024-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0014_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esfuerzoproyecto',
            name='esfuerzo_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
