# Generated by Django 5.1.2 on 2024-11-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0015_alter_esfuerzoproyecto_esfuerzo_estimado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EsfuerzoProyecto',
        ),
    ]
