# Generated by Django 5.1.2 on 2024-11-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0016_delete_esfuerzoproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
