# Generated by Django 5.1.2 on 2024-11-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0017_alter_projectplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
