# Generated by Django 5.1.2 on 2024-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0018_alter_projectplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='clientName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='endDate',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='objetive',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='startDate',
            field=models.DateField(blank=True, default=''),
        ),
    ]
