# Generated by Django 5.1.1 on 2024-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ambito', models.TextField(help_text='Descripción del alcance y expectativas del proyecto.')),
                ('caracteristicas_principales', models.TextField(help_text='Características principales del proyecto.')),
                ('limitaciones', models.TextField(help_text='Limitaciones del proyecto.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
