# Generated by Django 5.1.2 on 2024-11-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0002_projectplan_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectRisks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_identifier', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('risk_type', models.CharField(choices=[('technical', 'Técnico'), ('organizational', 'Organizativo'), ('financial', 'Financiero')], max_length=20)),
                ('identification_date', models.DateField(auto_now_add=True)),
                ('severity_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=10)),
                ('project_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='creadorAPP.projectplan')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('human', 'Recursos Humanos'), ('tools', 'Herramientas y Software'), ('infrastructure', 'Infraestructura y Servicios'), ('budget', 'Presupuesto'), ('documentation', 'Documentación y Procedimientos')], max_length=15, verbose_name='Tipo de Recurso')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Recurso')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity_estimated', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Estimada')),
                ('cost_estimated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Estimado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='creadorAPP.projectplan')),
            ],
        ),
    ]
