# Generated by Django 5.1.2 on 2024-11-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0003_task_end_date_task_start_date_projectrisks_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambitoproyecto',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ambiito', to='creadorAPP.projectplan'),
            preserve_default=False,
        ),
    ]
