# Generated by Django 5.1.1 on 2024-10-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creadorAPP", "0004_restriccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restriccion",
            name="descripcion",
            field=models.TextField(
                verbose_name='help_text="Descripcion de la restricción.'
            ),
        ),
        migrations.AlterField(
            model_name="restriccion",
            name="riesgo_identificado",
            field=models.TextField(
                verbose_name='help_text="Riesgo asociado con esta restricción.'
            ),
        ),
    ]
