# Generated by Django 5.1.2 on 2024-11-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0004_ambitoproyecto_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del miembro del equipo')),
                ('role', models.CharField(choices=[('manager', 'Gestor del proyecto'), ('developer', 'Desarrollador'), ('analyst', 'Analista'), ('tester', 'QA Tester'), ('other', 'Otro')], max_length=75, verbose_name='Rol del miembro del equipo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='creadorAPP.projectplan')),
            ],
        ),
    ]
