# Generated by Django 5.1.2 on 2024-11-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0005_workteammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplan',
            name='employeeName',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='employeeRole',
        ),
    ]
