# Generated by Django 5.1.2 on 2024-11-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorAPP', '0006_remove_projectplan_employeename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EsfuerzoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esfuerzo_estimado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('esfuerzo_real', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creadorAPP.projectplan')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_evento', models.CharField(choices=[('trabajo', 'Día de trabajo'), ('entrega', 'Entrega'), ('reunión', 'Reunión')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='creadorAPP.projectplan')),
                ('tasks', models.ManyToManyField(blank=True, related_name='eventos', to='creadorAPP.task')),
            ],
        ),
    ]
